version: '3.4'

services:
  monocker:
    container_name: monocker
    image: monocker
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      # Optional label to preface messages. Handy if you are running Monocker on different machines
      SERVER_LABEL: 'Dev'
      # Specify the messaging platform and details, or omit this if only wanting container logs
      MESSAGE_PLATFORM: 'telegram@your_bot_id@your_chat_id'
      # MESSAGE_PLATFORM: 'pushbullet@your_api_key@your_device_id'
      # MESSAGE_PLATFORM: 'pushover@your_user_key@your_app_api_token'
      # Filtering monitored containers - Optional - see readme
      LABEL_ENABLE: 'false'
      # Optional - only show when container state changes to being offline (paused, exited, running (unhealthy), or dead)
      ONLY_OFFLINE_STATES: 'false'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
